#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Wed Apr 29 14:18:22 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import matplotlib
from matplotlib.figure import Figure
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
import Console
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 600))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.fig = Figure()
        Console.ax = self.fig.add_subplot(111)
        Console.ax.grid(True)
        Console.ax.set_title("Osciloscopio virtual con PIC18F2550")
        Console.ax.set_ylim(-1,6)
        Console.ax.set_xlim(0,100)
        Console.ax.set_ylabel('Voltaje [V]')
        Console.ax.set_xlabel('Muestras')
        #plt.ylim(-1,6)
        #plt.grid() 
        self.Osciloscopio_Canvas = FigureCanvas(self.panel_1, wx.ID_ANY, self.fig)
        self.Osciloscopio_Canvas.set_window_title("Osciloscopio virtual con PIC18F2550")
        self.cmb_baud = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[ "50", "75", "110", "134", "150", "200", "300", "600", "1200", "1800", "2400", "4800", "9600", "19200", "38400", "57600", "115200","921600"], style=wx.CB_DROPDOWN)
        self.cmb_port = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=Console.serial_ports(), style=wx.CB_DROPDOWN)
        self.button_plot = wx.Button(self.panel_1, wx.ID_ANY, "Graficar")
        self.button_exit = wx.Button(self.panel_1, wx.ID_ANY, "Parar")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_button_plot, self.button_plot)
        self.Bind(wx.EVT_BUTTON, self.on_button_stop, self.button_exit)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Osciloscopio")
        self.button_plot.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.Osciloscopio_Canvas, 1, wx.ALL | wx.EXPAND, 3)
        sizer_4.Add((0, 0), 0, 0, 0)
        sizer_4.Add((0, 0), 0, 0, 0)
        sizer_2.Add(sizer_4, 0, wx.ALL | wx.EXPAND, 5)
        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Baudrate")
        sizer_3.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.cmb_baud, 0, 0, 0)
        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Puerto")
        sizer_3.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.cmb_port, 0, 0, 0)
        sizer_3.Add(self.button_exit, 0, wx.EXPAND, )
        sizer_3.Add(self.button_plot, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 0, wx.ALL | wx.EXPAND, 5)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade


    def on_button_plot(self, event):  # wxGlade: MyFrame.<event_handler>
        self.ani = Console.FuncAnimation(self.fig,Console.update,fargs=(self.cmb_port.GetStringSelection(),int(self.cmb_baud.GetStringSelection())),interval=1)
        self.Osciloscopio_Canvas.draw()
        

    def on_button_stop(self, event):  # wxGlade: MyFrame.<event_handler>
        self.ani.event_source.stop()
# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
